#!/bin/sh

escape () {
    printf '%q' "$1"
}

class="$(escape "$1")"
shift

if [ -n "$1" ]; then
    args="'$(escape "$1")'"
    shift
    for arg in $@; do
        args="$args, '$(escape "$arg")'"
    done
fi

./gradlew run -PtheClass="$class" -PtheArgs="[$args]"
